name: 'PR Label Release'
description: Use the Pull Request data to generate a new release.
author: Ian Welerson
branding:
  icon: git-merge
  color: red
inputs:
  github-token:
    description: github token
    required: false
    default: ${{ github.token }}
  v-prefix:
    description: prefix the version with v (Eg v1.2.3)
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'