name: 'PR Label Release'

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  pr_label_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Pull Request Label Release
        uses: ./
        with:
          v-prefix: true